import { ProjectConfig } from '../../core/types';

export const vitalchainConfig: ProjectConfig = {
  id: 'vitalchain',
  name: 'VitalChain',
  description: 'Cold Chain Integrity Monitoring System',
  theme: {
    primary: '#3b82f6',
    secondary: '#8b5cf6',
    warning: '#f59e0b',
    critical: '#ef4444',
    recovered: '#10b981',
  },

  metrics: [
    {
      key: 'temperature',
      name: 'Temperature',
      unit: '°C',
      min: -20,
      max: 10,
      normalMin: 2,
      normalMax: 8,
      warningMin: 0,
      warningMax: 10,
      criticalMin: -10,
      criticalMax: 15,
      precision: 1,
    },
    {
      key: 'humidity',
      name: 'Humidity',
      unit: '%',
      min: 0,
      max: 100,
      normalMin: 40,
      normalMax: 60,
      warningMin: 30,
      warningMax: 70,
      criticalMin: 20,
      criticalMax: 80,
      precision: 0,
    },
    {
      key: 'battery',
      name: 'Battery',
      unit: '%',
      min: 0,
      max: 100,
      normalMin: 20,
      normalMax: 100,
      warningMin: 10,
      warningMax: 100,
      criticalMin: 0,
      criticalMax: 5,
      precision: 0,
    },
    {
      key: 'signal',
      name: 'Signal Strength',
      unit: 'dBm',
      min: -120,
      max: -30,
      normalMin: -80,
      normalMax: -30,
      warningMin: -100,
      warningMax: -30,
      criticalMin: -120,
      criticalMax: -100,
      precision: 0,
    },
  ],

  thresholds: {
    temperature: {
      warning: 2,
      critical: 0,
    },
    humidity: {
      warning: 30,
      critical: 20,
    },
  },

  scenarios: [
    {
      id: 'normal',
      name: 'Normal Operation',
      description: 'Stable cold chain maintenance',
      duration: 60,
      speed: 1,
      steps: [
        {
          name: 'Steady State',
          phase: 'normal',
          startAt: 0,
          endAt: 60,
          metrics: {
            temperature: { start: 4, end: 4.5 },
            humidity: { start: 50, end: 52 },
            battery: { start: 85, end: 84 },
            signal: { start: -65, end: -66 },
          },
        },
      ],
    },
    {
      id: 'door_open',
      name: 'Door Open Incident',
      description: 'Temperature rises from door opening',
      duration: 90,
      speed: 1,
      steps: [
        {
          name: 'Normal',
          phase: 'normal',
          startAt: 0,
          endAt: 10,
          metrics: {
            temperature: { start: 4, end: 4 },
            humidity: { start: 50, end: 50 },
            battery: { start: 80, end: 80 },
            signal: { start: -65, end: -65 },
          },
        },
        {
          name: 'Early Signal',
          phase: 'early_signal',
          startAt: 10,
          endAt: 20,
          metrics: {
            temperature: { start: 4, end: 6, ease: 'easeInQuad' },
            humidity: { start: 50, end: 60, ease: 'easeInQuad' },
            battery: { start: 80, end: 80 },
            signal: { start: -65, end: -65 },
          },
        },
        {
          name: 'Warning',
          phase: 'warning',
          startAt: 20,
          endAt: 40,
          metrics: {
            temperature: { start: 6, end: 10, ease: 'easeInQuad' },
            humidity: { start: 60, end: 75, ease: 'easeInQuad' },
            battery: { start: 80, end: 79 },
            signal: { start: -65, end: -70 },
          },
        },
        {
          name: 'Critical',
          phase: 'critical',
          startAt: 40,
          endAt: 50,
          metrics: {
            temperature: { start: 10, end: 12 },
            humidity: { start: 75, end: 80 },
            battery: { start: 79, end: 78 },
            signal: { start: -70, end: -75 },
          },
        },
        {
          name: 'Alert',
          phase: 'alert',
          startAt: 50,
          endAt: 60,
          metrics: {
            temperature: { start: 12, end: 11 },
            humidity: { start: 80, end: 78 },
            battery: { start: 78, end: 77 },
            signal: { start: -75, end: -70 },
          },
        },
        {
          name: 'Recovery',
          phase: 'recovery',
          startAt: 60,
          endAt: 90,
          metrics: {
            temperature: { start: 11, end: 4, ease: 'easeOutQuad' },
            humidity: { start: 78, end: 50, ease: 'easeOutQuad' },
            battery: { start: 77, end: 76 },
            signal: { start: -70, end: -65 },
          },
        },
      ],
    },
    {
      id: 'compressor_failure',
      name: 'Compressor Failure',
      description: 'Cooling system failure leading to temperature rise',
      duration: 120,
      speed: 1,
      steps: [
        {
          name: 'Normal',
          phase: 'normal',
          startAt: 0,
          endAt: 15,
          metrics: {
            temperature: { start: 4, end: 4 },
            humidity: { start: 50, end: 50 },
            battery: { start: 90, end: 90 },
            signal: { start: -60, end: -60 },
          },
        },
        {
          name: 'Early Signal',
          phase: 'early_signal',
          startAt: 15,
          endAt: 30,
          metrics: {
            temperature: { start: 4, end: 5.5, ease: 'easeInCubic' },
            humidity: { start: 50, end: 55 },
            battery: { start: 90, end: 89 },
            signal: { start: -60, end: -62 },
          },
        },
        {
          name: 'Warning',
          phase: 'warning',
          startAt: 30,
          endAt: 55,
          metrics: {
            temperature: { start: 5.5, end: 10, ease: 'easeInCubic' },
            humidity: { start: 55, end: 70 },
            battery: { start: 89, end: 88 },
            signal: { start: -62, end: -68 },
          },
        },
        {
          name: 'Critical',
          phase: 'critical',
          startAt: 55,
          endAt: 70,
          metrics: {
            temperature: { start: 10, end: 15 },
            humidity: { start: 70, end: 85 },
            battery: { start: 88, end: 86 },
            signal: { start: -68, end: -75 },
          },
        },
        {
          name: 'Alert Dispatch',
          phase: 'alert',
          startAt: 70,
          endAt: 85,
          metrics: {
            temperature: { start: 15, end: 14 },
            humidity: { start: 85, end: 83 },
            battery: { start: 86, end: 85 },
            signal: { start: -75, end: -70 },
          },
        },
        {
          name: 'Recovery',
          phase: 'recovery',
          startAt: 85,
          endAt: 120,
          metrics: {
            temperature: { start: 14, end: 4, ease: 'easeOutCubic' },
            humidity: { start: 83, end: 50, ease: 'easeOutQuad' },
            battery: { start: 85, end: 82 },
            signal: { start: -70, end: -60 },
          },
        },
      ],
    },
    {
      id: 'freeze_fault',
      name: 'Freeze Fault',
      description: 'Temperature drops below safe range',
      duration: 100,
      speed: 1,
      steps: [
        {
          name: 'Normal',
          phase: 'normal',
          startAt: 0,
          endAt: 15,
          metrics: {
            temperature: { start: 4, end: 4 },
            humidity: { start: 50, end: 50 },
            battery: { start: 95, end: 95 },
            signal: { start: -55, end: -55 },
          },
        },
        {
          name: 'Early Signal',
          phase: 'early_signal',
          startAt: 15,
          endAt: 30,
          metrics: {
            temperature: { start: 4, end: 1, ease: 'easeInQuad' },
            humidity: { start: 50, end: 48 },
            battery: { start: 95, end: 94 },
            signal: { start: -55, end: -57 },
          },
        },
        {
          name: 'Warning',
          phase: 'warning',
          startAt: 30,
          endAt: 50,
          metrics: {
            temperature: { start: 1, end: -5, ease: 'easeInQuad' },
            humidity: { start: 48, end: 42 },
            battery: { start: 94, end: 93 },
            signal: { start: -57, end: -62 },
          },
        },
        {
          name: 'Critical',
          phase: 'critical',
          startAt: 50,
          endAt: 65,
          metrics: {
            temperature: { start: -5, end: -8 },
            humidity: { start: 42, end: 35 },
            battery: { start: 93, end: 91 },
            signal: { start: -62, end: -70 },
          },
        },
        {
          name: 'Alert',
          phase: 'alert',
          startAt: 65,
          endAt: 75,
          metrics: {
            temperature: { start: -8, end: -7 },
            humidity: { start: 35, end: 37 },
            battery: { start: 91, end: 89 },
            signal: { start: -70, end: -65 },
          },
        },
        {
          name: 'Recovery',
          phase: 'recovery',
          startAt: 75,
          endAt: 100,
          metrics: {
            temperature: { start: -7, end: 4, ease: 'easeOutCubic' },
            humidity: { start: 37, end: 50, ease: 'easeOutQuad' },
            battery: { start: 89, end: 85 },
            signal: { start: -65, end: -55 },
          },
        },
      ],
    },
  ],

  kpis: [
    {
      id: 'alert_time',
      label: 'Alert Detection Time',
      format: 'duration',
      value: '00:00',
      unit: 'seconds',
      target: 60,
    },
    {
      id: 'uptime',
      label: 'System Uptime',
      format: 'percentage',
      value: 99.8,
      unit: '%',
      target: 99.9,
    },
    {
      id: 'sensors_active',
      label: 'Active Sensors',
      format: 'number',
      value: 24,
      target: 24,
    },
    {
      id: 'events_handled',
      label: 'Events Handled',
      format: 'number',
      value: 0,
    },
  ],

  devices: [
    {
      id: 'sensor-01',
      name: 'Main Freezer',
      type: 'temperature_sensor',
      status: 'online',
      location: 'Facility A',
      battery: 85,
      signal: -65,
    },
    {
      id: 'sensor-02',
      name: 'Backup Freezer',
      type: 'temperature_sensor',
      status: 'online',
      location: 'Facility A',
      battery: 92,
      signal: -58,
    },
    {
      id: 'sensor-03',
      name: 'Transport Box',
      type: 'temperature_sensor',
      status: 'online',
      location: 'In Transit',
      battery: 78,
      signal: -75,
    },
  ],

  aiEngine: true,
  defaultScenario: 'normal',
  defaultSpeed: 1,
};
